name: Java CI with Gradle

on:
  push:
    branches:
      - master
      - release/*

  pull_request:
    branches:
      - master
      - release/*

env:
  BRANCH: ${{ env.GIT_BRANCH_NAME }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew
